name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      #run: docker build . --file acciones/action-a/Dockerfile --tag ping:$(date +%s)
      run: docker build -t contenedor . -f action-a/Dockerfile
