name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ./action-a
    - name: Build the Docker image
      run: docker build . --file /home/runner/work/acciones/acciones/action-a/Dockerfile --tag ping:$(date +%s)
